### ISSUE TITLE
Logo excluded from screenshot

### ISSUE THREAD

**Issue by prasanjitdash** [grinat/leaflet-simple-map-screenshoter#1]
Hi, I'm using a logo annotation plugin 'https://github.com/barisariburnu/leaflet-logo' for Leaflet maps.

This screenshoter works just fine (simple mode), however, excludes the logo from the captured image. How can I retain the logo?

Thanks for your time.

**Comment by grinat** [comment]
Hi, you can set hideElementsWithSelectors option with selectors wich you need hide. By default hide all controls: ['.leaflet-control-container']

For nothing hide:
```js
  var mapSimple = L.map('mapSimple').setView([40, -74], 6);
  L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png').addTo(mapSimple);

  L.simpleMapScreenshoter({
    // nothing to hide
    hideElementsWithSelectors: []
  }).addTo(mapSimple)
```

Hide only zoom buttons:
```js
  var mapSimple = L.map('mapSimple').setView([40, -74], 6);
  L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png').addTo(mapSimple);

  L.simpleMapScreenshoter({
    // hide only zoom buttons
    hideElementsWithSelectors: ['.leaflet-control-zoom']
  }).addTo(mapSimple)
```

**Comment by prasanjitdash** [comment]
Hi Grinat,

Many thanks, the solution works well.

However, a practical issue is there are too many selectors to be manually closed. Instead, is it possible to hide all and then selectively un-hide one or two? 
e.g., 
hideElementsWithSelectors: []
showElementsWithSelectors: ['.leaflet-control-logo']

**Comment by grinat** [comment]
I think, the introduction of a possible further option would create confusion.
