### ISSUE TITLE
Blob return type of takeScreenshot ignores mime type

### ISSUE THREAD

**Issue by jdkuhnke** [grinat/leaflet-simple-map-screenshoter#21]
The `takeScreenshot` function can return a DataURL of the specified type in the initial plugin options or the overwrite options of the function.  However, when return a Blob the mime type is ignored and the function always returns a png.

**Comment by grinat** [comment]
@jdkuhnke merged and published:  leaflet-simple-map-screenshoter (0.4.4)

**Comment by jdkuhnke** [comment]
Thanks, works for me!
