### ISSUE TITLE
Can't create screenshot using leaflet.gridlayer.googlemutant after Google updated API

### ISSUE THREAD

**Issue by ArtemTumanovNoveoGroup** [grinat/leaflet-simple-map-screenshoter#38]
I got 'May be map size very big on that zoom level' error when making screenshot for zoom 18 and bigger. Seems like updating dom-to-image-more to 2.12.0 fixes it. I have no access to push branch and create PR.

**Comment by grinat** [comment]
@ArtemTumanovNoveoGroup updated in leaflet-simple-map-screenshoter@0.5.0
