### ISSUE TITLE
Some margin/border shows up in the screenshot

### ISSUE THREAD

**Issue by berryhijwegen** [grinat/leaflet-simple-map-screenshoter#44]
With the following Leaflet map:
![image](https://user-images.githubusercontent.com/43235123/203642752-7990bc36-2e1e-43c6-ac98-03ab70cd6321.png)

I receive the following as output:
![image](https://user-images.githubusercontent.com/43235123/203642698-6905f435-cbb6-4cc3-a798-03258b049805.png)

Why does this happen?

**Comment by berryhijwegen** [comment]
This happened due to a border that tailwind assigned to every element on te page

**Comment by jayli3n** [comment]
> This happened due to a border that tailwind assigned to every element on te page

@berryhijwegen 
Can you remember how you fixed it in the end? Im also using tailwind with the same problem...

**Comment by jayli3n** [comment]
Found it if anyone is having the same issue

![image](https://user-images.githubusercontent.com/44139980/224214945-6959f425-50a6-4498-a7f6-845f7f884140.png)

**Comment by jayli3n** [comment]
Found the problem, tailwind sets a global border style to `solid` and width to `0`, just override it before screenshot, and then set it back:

![image](https://user-images.githubusercontent.com/44139980/224243956-f4c8001c-c4ea-4b1c-9132-629b011b5603.png)

![image](https://user-images.githubusercontent.com/44139980/224244004-4e7d1efd-7094-41e7-bb7e-47dc72a69410.png)


Would love to know if theres a proper fix within the package tho.
