### ISSUE TITLE
Unable to take screenshot with specific marker

### ISSUE THREAD

**Issue by flatbeats** [grinat/leaflet-simple-map-screenshoter#7]
Hi, first of all i really like this plugin!
Unfortunately i can't use it right now because i have a really strange error.
You can reproduce it using the following stackblitz:
https://stackblitz.com/edit/angular-p74qj2

if you take  screenshot while marker 1 is zoomed in, it works, but when you click the button to zoom on marker 2 and then take a screenshot it fails. 
In chrome the following error is shown:

> RangeError: Failed to execute 'getImageData' on 'CanvasRenderingContext2D': Out of memory at ImageData creation

On firefox:

> IndexSizeError: Index or size is negative or greater than the allowed amount

On Edge it doesn't work at all.

Strange enough if you hide marker one (use toggle marker1 button), then zoom to marker 2 you can take the screenshot successfully.
Also zooming out so that both markers are visible seems to work fine.

Cheers

Andreas

**Comment by grinat** [comment]
Hi, i found problem. When you zoom to the marker 2, map container scrollHeight and scrollWidth very big: 109934 26412
When you zoom to the marker 1, map container scrollHeight and scrollWidth: 743 1295

I will try to find a solution

**Comment by grinat** [comment]
Fix in 0.3.8 version
