### ISSUE TITLE
New version have issue

### ISSUE THREAD

**Issue by miko866** [grinat/leaflet-simple-map-screenshoter#8]
After update to the new version of your awesome package, I have an issue. After changing the zoom level and take a screenshot that makes only a screenshot with a white background. The output is in base64 and with AAA... content. 
I had no problems before.

**Comment by grinat** [comment]
You can place an example on https://stackblitz.com/ or something similar?

**Comment by miko866** [comment]
Sorry for the late answer, but I have a little time now. Unfortunately, I can't create a prototype because my project is very extensive. I use Vue2Leflet and there may be a bug there.
In my projects I draw a lot of figures on the map and plus I add some custom-created elements and when I wanted to create a screenshot I found that there was a problem with the catch. But version 0.3.7 works great.
